### ISSUE TITLE
adding the installing command

### ISSUE THREAD

**Issue by mehmeh-ctrl** [IHaskell/IHaskell#1323]
I wanted just to say that to my installation work I had to add one command:

curl -sSL https://get.haskellstack.org/ | sh
git clone https://github.com/gibiansky/IHaskell
cd IHaskell
pip3 install -r requirements.txt
stack install --fast
stack install ihaskell 
ihaskell install --stack

and it worked this time.

**Comment by vaibhavsagar** [comment]
It looks like you added a `stack install ihaskell` after `stack install --fast`, but I would expect that to be unnecessary. What issues were you running into before you added that line?

**Comment by mehmeh-ctrl** [comment]
ihaskell just wouldn't run, it was unrecognizable like the variable that wasn't initialized or a conda that wasn't in the path. Until I came into that solution, which provided ihaskell in the scope and I could run the last command in the aforementioned series. Maybe I should jump into Manjaro and try to document it? I was on Ubuntu 21.10.

**Comment by vaibhavsagar** [comment]
Closing, please reopen if required.
