### ISSUE TITLE
Broken Python package?

### ISSUE THREAD

**Issue by zeta-00** [IHaskell/IHaskell#1333]
apple@nixos> nix develop --system x86_64-darwin            
error: builder for '/nix/store/f85b1s304p8ywvv491n00d9r871b2hqv-python3.9-ju
pyter_server-1.11.1.drv' failed with exit code 1;
       last 10 log lines:
       >     from send2trash import send2trash
       >   File "/nix/store/3ny1n95wvmf4zmv9x8bb3yzxjzdi96sn-python3.9-Send2Trash-1.5.0/lib/python3.9/site-packages/send2trash/__init__.py", line 12, in <module>
       >     from .plat_osx import send2trash
       >   File "/nix/store/3ny1n95wvmf4zmv9x8bb3yzxjzdi96sn-python3.9-Send2Trash-1.5.0/lib/python3.9/site-packages/send2trash/plat_osx.py", line 17, in <module>
       >     GetMacOSStatusCommentString = Foundation.GetMacOSStatusCommentString
       >   File "/nix/store/kzcwq3q7clcfhirvxakjknw5hz4lwprb-python3-3.9.6/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
       >     func = self.__getitem__(name)
       >   File "/nix/store/kzcwq3q7clcfhirvxakjknw5hz4lwprb-python3-3.9.6/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
       >     func = self._FuncPtr((name_or_ordinal, self))
       > AttributeError: dlsym(RTLD_DEFAULT, GetMacOSStatusCommentString): symbol not found
       For full logs, run 'nix log /nix/store/f85b1s304p8ywvv491n00d9r871b2hqv-python3.9-jupyter_server-1.11.1.drv'.
error: 1 dependencies of derivation '/nix/store/bqiwvz425q4sy16nazbb62m00vcr
n53a-python3-3.9.6-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/88fh5fa7yryql7d6k00cnagn5dfg
zrpa-ghc-shell-for-ihaskell-0.10.2.2-env.drv' failed to build

**Comment by zeta-00** [comment]
I'm using mach-nix which has solved my python development issues, so combining it with IHaskell will solve Python package issues like this?

Thanks in advance for the help.

**Comment by zeta-00** [comment]
apple@nixos> nix-info -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.3.0, macOS 12.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(apple): `""`
 - channels(root): `"darwin, home-manager, nixpkgs-unstable-21.11pre311289.503209808cd, nixpkgs-21.11pre309670.253aecf69ed"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by zeta-00** [comment]
I have nix setup to fallback on `x86_64-darwin`, if something does not work natively on the `default` `aarch64-darwin`.

**Comment by zeta-00** [comment]
```
{
  inputs = {
    ihaskell.url = "github:IHaskell/IHaskell";
    ihaskell.inputs.nixpkgs.follows = "nixpkgs";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    utils.url = "github:gytis-ivaskevicius/flake-utils-plus/v1.3.1";
  };

  outputs = inputs@{ self, ihaskell, utils, ... }:
    utils.lib.mkFlake {
      inherit self inputs;
      outputsBuilder = channels: {
        devShell = ihaskell.devShell.x86_64-darwin;
      };
    };
}
```

**Comment by zeta-00** [comment]
^ The above nix flake fixes the issue, `Randy Eckenrode` in Matrix chat channel `Nix on macOS` helped me fix this issue.

**Comment by zeta-00** [comment]
Go ahead and close this issue if you want, thanks again for the help, this IHaskell tool is awesome, I'm trying to get it working in Emacs/Emacs-IPython-Notebook/Eglot now, so I'll let you all know if I'm able to get it working correctly.

**Comment by vaibhavsagar** [comment]
This doesn't look like an issue with IHaskell, closing.
