### ISSUE TITLE
IHaskell kernel is not showing up in Emacs-IPython-Notebook:

### ISSUE THREAD

**Issue by zeta-00** [IHaskell/IHaskell#1334]
https://github.com/IHaskell/IHaskell/issues/1333

After this issue was resolved, with the flake at the bottom of the issue I was able to install IHaskell without any errors, but for some reason Emacs-IPython-Notebook is not showing the IHaskell kernel?
It's only showing the IPython kernel?

Thanks in advance for the help.

And being that IHaskell comes package with haskell-language-server, it should work fine with `Eglot`, correct?

I got Eglot working with haskell-language-server in regular haskell file programs, so I don't see why it should not work with IHaskell and .ipynb files, correct?

**Comment by zeta-00** [comment]
Note: I also ran `jupyter-notebook` in the terminal, to make sure that a jupyter server was running in the background.

At this point I don't know.

Thanks in advance for the help.

**Comment by vaibhavsagar** [comment]
There is no interoperability between IHaskell and haskell-language-server, so it probably won't work with `Eglot`. I'm unable to provide support for your Emacs integration.
