### ISSUE TITLE
Mybinder doesn't load properly

### ISSUE THREAD

**Issue by tmainiero** [IHaskell/IHaskell#1341]
Following the mybinder.org link in the readme leads to the error log: 
``Could not resolve ref for gh:gibiansky/IHaskell/mybinder. Double check your URL. GitHub recently changed default branches from "master" to "main".``

**Comment by vaibhavsagar** [comment]
I reinstated https://github.com/IHaskell/IHaskell/tree/mybinder so it should work again!
