### ISSUE TITLE
Diagrams makes kernel crash

### ISSUE THREAD

**Issue by reubenharry** [IHaskell/IHaskell#1345]
When I use the `diagram` function to display a diagram (I'm following the code here: https://github.com/IHaskell/IHaskell/blob/master/notebooks/IHaskell.ipynb), my kernel crashes. I was wondering if other people were able to display diagrams in a jupyter + IHaskell notebook. (This is on GHC 8.10.7)

**Comment by vaibhavsagar** [comment]
Works for me: 
![ihaskell-diagrams](https://user-images.githubusercontent.com/1525767/168708962-09a82468-63de-41f1-ac79-55243478d9c1.png)

I'm using [this notebook](https://github.com/vaibhavsagar/notebooks/blob/99e49b27f9755f7343701ede191fc82513dba472/chart-diagrams/Fib.ipynb), which you might be able to try yourself depending on your familiarity with Nix.

How did you install IHaskell, and was there any useful console output indicating what the issue was around the time the kernel crashed? I suspect a library incompatibility.

**Comment by reubenharry** [comment]
Thanks for your help!

The error is:

```
Info 20:08:14: Dispose Kernel process
Error 20:08:14: Raw kernel process exited code: undefined
Error 20:08:14: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/Users/Reuben.Cohn-Gordon/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:426364)
	at /Users/Reuben.Cohn-Gordon/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:328821
	at Map.forEach (<anonymous>)
	at y._clearKernelState (/Users/Reuben.Cohn-Gordon/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:328807)
	at y.dispose (/Users/Reuben.Cohn-Gordon/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:322239)
	at /Users/Reuben.Cohn-Gordon/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:188455
	at t.swallowExceptions (/Users/Reuben.Cohn-Gordon/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:1:139012)
	at dispose (/Users/Reuben.Cohn-Gordon/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:188434)
	at t.RawSession.dispose (/Users/Reuben.Cohn-Gordon/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:104:352774)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)]
Info 20:08:14: Cancel all remaining cells due to dead kernel
Info 20:08:14: Cancel pending cells
Info 20:08:14: Cell 2 executed with state Success
```

but there's a relevant warning, namely:

```
Disabling IHaskell widget support due to an encountered error:
The installed IHaskell support libraries do not match the instance of IHaskell you are running.
This *may* cause problems with functioning of widgets or rich media displays.
This is most often caused by multiple copies of IHaskell being installed simultaneously in your environment.
To resolve this issue, clear out your environment and reinstall IHaskell.
If you are installing support libraries, make sure you only do so once:
    # Run this without first running `stack install ihaskell`
    stack install ihaskell-diagrams
```

Should I be using a global stack version if IHaskell, or IHaskell from the environment of my project? (and same for ihaskell-diagrams, etc). I only see the global IHaskell appear as a kernel option.

Maybe I'll try the nix solution...

**Comment by vaibhavsagar** [comment]
That error is caused by having different IHaskell installations using different versions of GHC. I would suggest checking `~/.stack/global-project/stack.yaml` and ensuring that the GHC version in use is the same one: https://github.com/IHaskell/IHaskell#the-kernel-keeps-dying-ihaskell--stack.

**Comment by reubenharry** [comment]
Thanks! Also, nix with your repo worked :)
