### ISSUE TITLE
remove monoid-extras-0.6 from stack.yaml extra deps

### ISSUE THREAD

**Issue by Sorokin-Anton** [IHaskell/IHaskell#1357]
IHaskell can be built with `stack --resolver nightly-2022-07-12 install` and used with GHC 9.2.3, but for doing this you need to delete `monoid-extras-0.6 ` from extra deps or add `allow-newer`. This package is currently not used in project, so I think we need to remove this dependency

**Comment by vaibhavsagar** [comment]
Sure, would you be willing to make a PR?

**Comment by vaibhavsagar** [comment]
I think we've since removed this dependency.
