### ISSUE TITLE
Kernel dies with Missing file: …/platformConstants

### ISSUE THREAD

**Issue by essandess** [IHaskell/IHaskell#1366]
I'm building iHaskell with `stack` and a system `ghc` version 9.4.2 on macOS.

The build and binary work, but kernel dies in Jupyter with the error:
```sh
ihaskell: Missing file: /opt/local/lib/ghc-9.4.2/lib/platformConstants
```

The version is:
```sh
ihaskell -V
0.10.2.2
```

Possibly related #804

**Comment by vaibhavsagar** [comment]
Did you follow the rest of the comments in the issue that you linked to? We don't support GHC 9.4 yet so I suspect the same issue has occurred again where you've installed IHaskell with GHC 9.2 when your system GHC is 9.4.

**Comment by essandess** [comment]
> Did you follow the rest of the comments in the issue that you linked to? We don't support GHC 9.4 yet so I suspect the same issue has occurred again where you've installed IHaskell with GHC 9.2 when your system GHC is 9.4.

Thanks. I can confirm that I built and installed IHaskell with my system ghc 9.4.2.

**Comment by vaibhavsagar** [comment]
When you say you built and installed it, you mean that you ran `stack install`? I think that would use GHC 8.10.7! As you can see from https://www.stackage.org/, there is no resolver for GHC 9.4, and the current LTS is on GHC 9.0 (not even 9.2 yet).

**Comment by essandess** [comment]
> When you say you built and installed it, you mean that you ran `stack install`? I think that would use GHC 8.10.7! As you can see from https://www.stackage.org/, there is no resolver for GHC 9.4, and the current LTS is on GHC 9.0 (not even 9.2 yet).

We use `--system-ghc` with the IHaskell `stack` build so that it’s built with the same `ghc` it’s run with:

https://github.com/macports/macports-ports/blob/725cddc569e21d1b1c8860e3ebd332893c5c53a3/_resources/port1.0/group/haskell_stack-1.0.tcl#L50

**Comment by essandess** [comment]
I tried a `cabal`-based build and got prey far (after patching the `packages` from `stack.yaml` into `ihaskell.cabal`), but ran into this native `ihaskell` issue on `ghc` version 9.4.1:
```sh
:info:build [15 of 25] Compiling IHaskell.Eval.Util ( src/IHaskell/Eval/Util.hs, /opt/local/var/macports/build/_opt_local_ports_devel_ihaskell/ihaskell/work/dist/build/x86_64-osx/ghc-9.4.2/ihaskell-0.10.2.2/build/IHaskell/Eval/Util.o, /opt/local/var/macports/build/_opt_local_ports_devel_ihaskell/ihaskell/work/dist/build/x86_64-osx/ghc-9.4.2/ihaskell-0.10.2.2/build/IHaskell/Eval/Util.dyn_o )
:info:build src/IHaskell/Eval/Util.hs:488:32: error:
:info:build     • Couldn't match expected type ‘[ClsInst]’
:info:build                   with actual type ‘GHC.Core.InstEnv.InstEnv’
:info:build     • In the second argument of ‘nubBy’, namely ‘clsInsts’
:info:build       In the expression: nubBy instEq clsInsts
:info:build       In an equation for ‘clsInsts'’: clsInsts' = nubBy instEq clsInsts
:info:build     |
:info:build 488 |       clsInsts' = nubBy instEq clsInsts
:info:build     |                                ^^^^^^^^
:info:build src/IHaskell/Eval/Util.hs:489:45: error:
:info:build     • Couldn't match expected type ‘GHC.Core.InstEnv.InstEnv’
:info:build                   with actual type ‘[ClsInst]’
:info:build     • In the expression: clsInsts'
:info:build       In the ‘ic_instances’ field of a record
:info:build       In the ‘hsc_IC’ field of a record
:info:build     |
:info:build 489 |   in hscEnv { hsc_IC = ic { ic_instances = (clsInsts', famInsts) } }
:info:build     |                                             ^^^^^^^^^
```

**Comment by vaibhavsagar** [comment]
Hi, I just fixed this error as part of adding GHC 9.4 support in https://github.com/IHaskell/IHaskell/pull/1376, you should be able to get further if you try again with the latest `master`.

**Comment by essandess** [comment]
> Hi, I just fixed this error as part of adding GHC 9.4 support in #1376, you should be able to get further if you try again with the latest `master`.

Thanks. The `stack` build completes, but the kernel fails with the error:
```sh
ihaskell: Missing file: /opt/local/lib/ghc-9.4.2/lib/platformConstants
```

The `cabal` build now fails with the error:
```sh
:info:build src/IHaskell/Eval/Parser.hs:30:1: error:
:info:build     Could not find module ‘Language.Haskell.GHC.Parser’
:info:build     Perhaps you meant
:info:build       Language.Haskell.TH.Ppr (needs flag -package-id ghc-lib-parser-9.4.2.20220822)
:info:build       Language.Haskell.TH.Ppr (needs flag -package-id template-haskell-2.19.0.0)
:info:build       Language.Haskell.TH.PprLib (needs flag -package-id ghc-lib-parser-9.4.2.20220822)
:info:build     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
:info:build    |
:info:build 30 | import           Language.Haskell.GHC.Parser
:info:build    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by vaibhavsagar** [comment]
That module is provided by `ghc-parser` which is also in this repo.

**Comment by essandess** [comment]
> That module is provided by `ghc-parser` which is also in this repo.

Thanks! Have this working with `cabal` now. Also note that I believe a patch is necessary in [ihaskell.cabal](https://github.com/IHaskell/IHaskell/blob/master/ihaskell.cabal) to add directory dependencies for a `cabal` build. Please see https://github.com/macports/macports-ports/pull/16364. 

For a `stack` version 2.9.1 build, I still observe this issue:
```sh
ihaskell: Missing file: /opt/local/lib/ghc-9.4.2/lib/platformConstants
```

**Comment by vaibhavsagar** [comment]
No, I don't think we need that patch. `ihaskell` is a separate project to `ghc-parser` and declares a dependency on it, if you have to change things on your end to get it to build correctly then that seems like a MacPorts-specific concern.

**Comment by essandess** [comment]
> No, I don't think we need that patch. `ihaskell` is a separate project to `ghc-parser` and declares a dependency on it, if you have to change things on your end to get it to build correctly then that seems like a MacPorts-specific concern.

Thanks, you're right. Not a MacPorts thing, my own mistake. Fixed in the MacPorts PR.

**Comment by vaibhavsagar** [comment]
Closing, please reopen if required.
