### ISSUE TITLE
New ghc-parser release?

### ISSUE THREAD

**Issue by thomasjm** [IHaskell/IHaskell#1367]
Currently `ghc-parser-0.2.3.0` on Hackage has an upper bound of `ghc < 9.1`. This prevents IHaskell from being built on the latest `nixpkgs-unstable` branch against GHC 9.2.

It looks like the current in-tree `ghc-parser` has been updated to support 9.2. Could you tag a new `ghc-parser` release and put it on Hackage? Thanks!

**Comment by vaibhavsagar** [comment]
I've uploaded new versions of `ghc-parser`, `ipython-kernel`, and `ihaskell`.

**Comment by thomasjm** [comment]
Awesome, thanks!
