### ISSUE TITLE
openBinaryFile: resource busy (file is locked)

### ISSUE THREAD

**Issue by jamesdbrock** [IHaskell/IHaskell#1370]
I'm trying to upgrade https://github.com/jamesdbrock/ihaskell-notebook from IHaskell 2022-03-02 to IHaskell 2022-09-12 and I find that when I try to test a lot of the `Display` extensions, they all fail to display in the same way.

### Charts

```
/tmp/ihaskell-chart47-0.png: openBinaryFile: resource busy (file is locked)
```

### Diagrams

```
/tmp/ihaskell-diagram105-0.png: openBinaryFile: resource busy (file is locked)
```

### Gnuplot

```
/tmp/ihaskell-gnuplot152-0.png: openBinaryFile: resource busy (file is locked)
```

Maybe this is related to #1359 ?

**Comment by jamesdbrock** [comment]
#1359 introduced the use of `withSystemTempFile`.

The `withSystemTempFile` function actually opens the file and passes a filename and the open file handle to the “with” function. But since that PR, in the “with” function we're ignoring the open file handle and trying to reopen the filename for writing and reading.

So I think that’s why this error is happening.

We are using APIs functions like `renderCairo` which take a filename, not a handle, so we can’t use the handle from `withSystemTempFile`. Maybe a better approach would be to use `withSystemTempDirectory` instead.

**Comment by jamesdbrock** [comment]
Another thing I just noticed is that in https://hub.docker.com/r/jupyter/base-notebook , the `/tmp` directory is not mounted to a `tmpfs` file system, so these functions are probably actually round-tripping the display images to the hard drive, which is horrifying.

**Comment by jamesdbrock** [comment]
The best solution would be to refactor all this stuff so it doesn't write to any temp files. Writing to the temp files is totally unnecessary. Might require improving dependency packages like [`renderCairo`](https://hackage.haskell.org/package/diagrams-cairo-1.4.1/docs/Diagrams-Backend-Cairo.html#v:renderCairo) which can only write to a filename instead of just returning a `ByteString`, which would be so much better.

**Comment by vaibhavsagar** [comment]
Oh no! Do you think we should revert https://github.com/IHaskell/IHaskell/pull/1359 for now?

**Comment by jamesdbrock** [comment]
I'm looking into this, I'll try to make a PR.

**Comment by jamesdbrock** [comment]
I also was thinking about related problems in #1248 .

I'm working on using something like `withSystemTempDirectory` to solve issue #1358 , and I would rather do that than revert.
