### ISSUE TITLE
VS Code raw code cells

### ISSUE THREAD

**Issue by jamesdbrock** [IHaskell/IHaskell#1381]
In the Microsoft VS Code [Jupyter Extension](https://github.com/microsoft/vscode-jupyter), IHaskell kernel notebooks don’t support raw code cells.

I’m working out the issue here https://github.com/microsoft/vscode-jupyter/issues/10357

**Comment by vaibhavsagar** [comment]
It looks like the linked issue has been fixed? Please reopen if required.
