### ISSUE TITLE
Using IHaskell as a plugin?

### ISSUE THREAD

**Issue by hyperswine** [IHaskell/IHaskell#1391]
So as I understand it, IHaskell is made to be its own version of jupyter instead of extending a jupyter install, and so you have to run `stack exec jupyter -- notebook` for a haskell kernel in a jupyter environment. Is there a way to make IHaskell a kernel that can be loaded by any jupyter instance? Like if I wanted to run `jupyter lab`, I'd have access to python, julia, racket, etc. I also want haskell to be a loadable kernel there too

**Comment by jamesdbrock** [comment]
`ihaskell` is a Jupyter kernel. It will install itself with, for example, `stack exec ihaskell -- install --stack`. After that you can see the installed kernel:

```sh
$ jupyter-kernelspec list
Available kernels:
  python3    /opt/conda/share/jupyter/kernels/python3
  haskell    /usr/local/share/jupyter/kernels/haskell
```

**Comment by hyperswine** [comment]
Unfortunately Im having issues building ihaskell with `stack install --fast` on popos 22.04. Im getting:

```
Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7: No cabal file found.
Please create a package description file <pkgname>.cabal

    Process exited with code: ExitFailure 1
```

on the `zeromq4-haskell` part. Any idea what could be the problem?

**Comment by vaibhavsagar** [comment]
You haven't included the actual error message.
