### ISSUE TITLE
Strange `:info` behavior

### ISSUE THREAD

**Issue by SmartHypercube** [IHaskell/IHaskell#1394]
# How to reproduce
1. `pip install jupyterlab jupyterlab-widgets notebook`. (Versions: [requirements.txt](https://github.com/IHaskell/IHaskell/files/10674898/requirements.txt))
2. Build and install IHaskell. (Version: current master, 1c22a87)
3. `jupyter-notebook` and create a new notebook. (Note that I'm not using Jupyter Lab.)
4. See below.

# If `:opt pager` (the default) is used
`:info Maybe` will never produce any output.

# If `:opt no-pager` is used
![image](https://user-images.githubusercontent.com/7789364/217245295-d8bfc858-c8d3-4bf1-a016-dfe1857312cc.png)
Only the first `:info` has pretty output. Also, each time `:info` is executed, the first `:info`'s output is appended with a new copy.

# Other strange things
During testing, I also noticed that sometimes there will be a popup at the bottom:
![image](https://user-images.githubusercontent.com/7789364/217249234-760f5627-6321-489a-a2a6-480c0969b42e.png)
Sometimes its content is pretty, sometimes it's not (like the screenshot).

Sometimes executing `:info` produces nothing, but executing the next cell makes the output of `:info` shows up.

Some behaviors seem to be related to the state of browser window and cannot be reliably reset by clicking "restart the kernel". For example, after restarting the kernel, the (previous session's) output of `:info` will continue to be appended with new copies.

I have no idea how to describe the current behavior... It seems too unstable. What should be the expected behavior anyway?

**Comment by thomasjm** [comment]
FYI I've got an attempt to improve this situation in #1414

**Comment by vaibhavsagar** [comment]
I believe this has been fixed by @thomasjm's changes:

![pager_fixed](https://github.com/IHaskell/IHaskell/assets/1525767/7b41c97d-da03-4353-9e77-f1b62b5df646)

Please reopen if you're still experiencing issues on the latest IHaskell.
