### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by jamesdbrock** [IHaskell/IHaskell#1396]
I've started having trouble running the IHaskell kernel in `docker`.

```
ihaskell: mmap 8192 bytes at (nil): Cannot allocate memory
ihaskell: Try specifying an address with +RTS -xm<addr> -RTS
ihaskell: m32_alloc: Failed to map pages for 5136 bytes: Cannot allocate memory
ihaskell: loadArchive "/opt/stack/snapshots/x86_64-linux-tinfo6/9b5711e3ad54387c89bf7987f516d17dd7431d9cb225ad7ae63da50aac53294d/8.10.7/lib/x86_64-linux-ghc-8.10.7/comonad-5.0.8-JCC8ZHJpGKdB9Y7ptpELB/libHScomonad-5.0.8-JCC8ZHJpGKdB9Y7ptpELB.a": failed
```

The only other people on the internet who seem to be having similar trouble are people on this archlinux forum. They think that it has something to do with the Linux 6.1 kernel. https://bbs.archlinux.org/viewtopic.php?id=282429

**Comment by jamesdbrock** [comment]
Other reports of similar trouble:

https://github.com/docker/for-linux/issues/1443

**Comment by jamesdbrock** [comment]
This always happens with GHC 8 and GHC 9 and `docker` and `podman` on my local machine, which is running Linux 6.1.11-200.fc37.x86_64.

This never happens on the Binder service, or my laptop running Linux 5.15.94.

I am starting to think this is in fact cause by some Linux kernel 6.1 behavior.

**Comment by vaibhavsagar** [comment]
This appears to be an upstream issue.
