### ISSUE TITLE
HLS for GHC 9

### ISSUE THREAD

**Issue by jamesdbrock** [IHaskell/IHaskell#1398]
`nix develop .#ihaskell-dev-921` fails because it can't find a `haskell-language-server`.

If I try to update the HLS flake input,

```
$ nix flake lock --update-input hls
warning: updating lock file '/home/jbrock/work/oth/IHaskell/flake.lock':
• Updated input 'hls':
    'github:haskell/haskell-language-server/311107eabbf0537e0c192b2c377d282505b4eff1' (2021-11-18)
  → 'github:haskell/haskell-language-server/f63627fa811a47b1bdc12fa65575ced1519d40c5' (2023-02-22)
```

then the new HLS flake input doesn't support any GHC 8 versions. What to do? Time to drop GHC 8 support?

**Comment by vaibhavsagar** [comment]
Yes, I don't think upstream has fixed the `zeromq4-haskell` issue yet at least.

**Comment by jamesdbrock** [comment]
Upgrading to current __nixos-unstable__ is blocked on this issue https://github.com/timbod7/haskell-chart/issues/243

**Comment by vaibhavsagar** [comment]
@thomasjm has completely redone `flake.nix` so this should no longer be an issue.
