### ISSUE TITLE
nix run github:IHaskell/IHaskell#ihaskell -- install

### ISSUE THREAD

**Issue by jamesdbrock** [IHaskell/IHaskell#1399]
I think it's possible to “install” an IHaskell kernel with the command

```
nix run github:IHaskell/IHaskell#ihaskell -- install
```

Maybe we should think about documenting and supporting this usage for people who want to want to “install” a kernel the [old-fashioned](https://ipython.readthedocs.io/en/stable/install/kernel_install.html) way by copying it to their `~/.local/share/jupyter` directory.

**Comment by vaibhavsagar** [comment]
I don't think there are that many people who use Nix flakes and also want to install things globally.

**Comment by jamesdbrock** [comment]
That's probably right.
