### ISSUE TITLE
New ghc-parser release?

### ISSUE THREAD

**Issue by thomasjm** [IHaskell/IHaskell#1405]
Currently `ghc-parser-0.2.4.0` on Hackage has an upper bound of `ghc < 9.3`. This prevents IHaskell from being built on the latest `nixpkgs-unstable` branch against GHC 9.4.

It looks like the current in-tree `ghc-parser` has been updated to support 9.4. Could you tag a new `ghc-parser` release and put it on Hackage? Thanks!

(Similar to #1367)

**Comment by thomasjm** [comment]
@vaibhavsagar friendly ping on this?

**Comment by vaibhavsagar** [comment]
Apologies for the delay, I just got back from a long overseas trip. Published as [`ghc-parser-0.2.5.0`](https://hackage.haskell.org/package/ghc-parser-0.2.5.0). I also released [`ihaskell-0.10.4.0`](https://hackage.haskell.org/package/ihaskell-0.10.4.0).

**Comment by thomasjm** [comment]
Thanks!
