### ISSUE TITLE
Nix instructions seem wildly out of date

### ISSUE THREAD

**Issue by danwdart** [IHaskell/IHaskell#1408]
- They suggest 8.6.5 when 9.6 is supported
- They point to channel version 20.03 which is also completely unsupported

Could that be tested and updated please? I don't know if the caches are up to date either.

Thanks

**Comment by vaibhavsagar** [comment]
Thanks for pointing this out, I've updated the instructions in https://github.com/IHaskell/IHaskell/pull/1409. Unlike the README which I have to remember to manually update, we populate the caches in CI as part of [the Nix workflow](https://github.com/IHaskell/IHaskell/blob/c547ee2fdc0a09cf4129b19292147fec38527a55/.github/workflows/nix.yml), so they are always up to date.
