### ISSUE TITLE
Jupyter cannot connect to kernel from outside IHaskell folder.

### ISSUE THREAD

**Issue by S4815162342** [IHaskell/IHaskell#1411]
Hi, I had the IHaskell kernel working fine for a while on my PC. I tried using it today and it wouldn't connect.

I re-installed the kernel and now it does work fine from inside the IHaskell folder. However, if I try to run any jupyter notebook from outside that folder, it does not work.

Help?

**Comment by vaibhavsagar** [comment]
Can you provide the console output of running IHaskell inside and outside the folder?

**Comment by vaibhavsagar** [comment]
Closing, please reopen if required.
