### ISSUE TITLE
Tests run "forever"

### ISSUE THREAD

**Issue by alaendle** [IHaskell/IHaskell#1413]
Hi the hspec process keeps running "forever" in Stackage.
I haven't tried to reproduce outside Stackage yet but let me report this here first and follow up with more details later if needed.
I think basically your GitHub CI Actions timing out after one day exposing the same problems.
For now I've disabled the test run on stackage.

**Comment by vaibhavsagar** [comment]
We haven't changed the test suite recently, so I don't see why this would be happening.

**Comment by alaendle** [comment]
You might be right, I didn't look closely at the GitHub Actions (they just don't work because no suitable runner can be found anymore) and I couldn't reproduce the problem locally - the tests were fast. The tests are not evaluated by Stackage anyway (since https://github.com/IHaskell/IHaskell/issues/551) and locally I still get errors:

```
Failures:

  src/tests/IHaskell/Test/Eval.hs:49:9: 
  1) Code Evaluation evaluates flags
       Expected result to have 0 results. Got [ManyDisplay [Display [DisplayData,DisplayData]]]

  To rerun use: --match "/Code Evaluation/evaluates flags/"

  src/tests/IHaskell/Test/Eval.hs:49:9: 
  2) Code Evaluation immediately applies language extensions
       Expected result to have 0 results. Got [ManyDisplay [Display [DisplayData,DisplayData]]]

  To rerun use: --match "/Code Evaluation/immediately applies language extensions/"

Randomized with seed 1416682764
```

This only as an indication. I am closing this issue - and will continue to skip the stackage side tests.

Still, I could swear I saw IHaskell processes running for hours on our build machine.

**Comment by vaibhavsagar** [comment]
We do run tests as part of the Nix build in CI and those continue to pass, so I'm very curious about the failures you are seeing.

**Comment by alaendle** [comment]
At least I can reproduce the failed tests (also on another machine):
```
Failures:

  src/tests/IHaskell/Test/Eval.hs:49:9: 
  1) Code Evaluation evaluates flags
       Expected result to have 0 results. Got [ManyDisplay [Display [DisplayData,DisplayData]]]

  To rerun use: --match "/Code Evaluation/evaluates flags/"

  src/tests/IHaskell/Test/Eval.hs:49:9: 
  2) Code Evaluation immediately applies language extensions
       Expected result to have 0 results. Got [ManyDisplay [Display [DisplayData,DisplayData]]]

  To rerun use: --match "/Code Evaluation/immediately applies language extensions/"

Randomized with seed 1942349483
```
Just build with stack and latest nightly-2023-08-04 and the two tests fail. Or just use the [verirfy-package](https://github.com/commercialhaskell/stackage/blob/master/verify-package) script and run `./verify-package ihaskell`.

**Comment by vaibhavsagar** [comment]
I think I've fixed the issue you've pointed out here, it had to do with [how we handle package flags](https://github.com/IHaskell/IHaskell/commit/7de07ec3a3b11153ed23b83ce20df2a96229c92c#diff-32a0d28b77b0e11700748294ffad76e0abb50d13d99f79ec18478bf5e64c7179L367). Very strange that I wasn't seeing this as part of the Nix CI, I believe it might be some Stack-specific behaviour we weren't exercising before.
