### ISSUE TITLE
IHaskell not building

### ISSUE THREAD

**Issue by wstomv** [IHaskell/IHaskell#1435]
I updated my local IHaskell repo (on macOS Sonoma) and tried to build it with
``` shell
stack install --fast
```
GHC 9.4.7 is installed, and the resolvers in my global `stack.yaml` and the one in the IHaskell directory both use `lts 21.21` for GHC 9.4.7.
This gave me the following error:
```
Error: [S-4804]
       Stack failed to construct a build plan.
       
       While constructing the build plan, Stack encountered the following errors. The
       'Stack configuration' refers to the set of package versions specified by the
       snapshot (after any dropped packages, or pruned GHC boot packages; if a boot
       package is replaced, Stack prunes all other such packages that depend on it) and
       any extra-deps:
       
       In the dependencies for Chart-cairo-1.9.3:
         * lens must match >=3.9 && <5.1, but lens-5.2.3 is in the Stack configuration
           (latest matching version is 5.0.1).
       needed due to ihaskell-charts-0.3.0.1 -> Chart-cairo-1.9.3
       
       Some different approaches to resolving some or all of this:
       
         * To ignore all version constraints and build anyway, in
           /Users/wstomv/.stack/config.yaml (global configuration) or
           /Users/wstomv/Repositories/IHaskell/stack.yaml (project-level configuration),
           set allow-newer: true.
         
         * To ignore certain version constraints and build anyway, also add these
           package names under allow-newer-deps: Chart-cairo.
         
         * Recommended action: try adding the following to your extra-deps in
           /Users/wstomv/Repositories/IHaskell/stack.yaml (project-level configuration):
           
           - lens-5.0.1@sha256:63ed57e4d54c583ae2873d6892ef690942d90030864d0b772413a1458e98159f,15544
```
I have no clue what is going on here and how to address it.
I tried some of the suggested alternate approaches, but then things got worse.

Doesn't stack install dependencies as needed, and shouldn't it then be able to come up with a build plan, assuming that the IHaskell repo is in a consistent state?

Some help would be appreciated.

**Comment by wstomv** [comment]
So, a few hours later, with the help of some web searches, I managed to fix this.

1. Use `--extra-...` flags (shown in the README; my bad for not doing that in the first place):
   ``` shell
   $ stack install --fast --extra-include-dirs ${HOMEBREW_PREFIX}/include --extra-lib-dirs ${HOMEBREW_PREFIX}/lib
   ```

3. In `stack.yaml`, I bumped the version of `Chart-cairo-1.9.3` to 1.9.4.

   This was needed, because `stack.yaml` is configured (out-of-the-box) with `resolver: lts-21.21`
   (with GHC 9.4.7), which includes `lens-5.2.3`,
   which exceeds the requirements for `Chart-cairo-1.9.3`, but `lens-5.2.3` will work with 1.9.4.

   I suggest to fix this on the IHaskell side. (How did it work for others?)

4. Update my XCode command-line tools, which is a bit more complicated nowadays.

   See: https://developer.apple.com/forums/thread/677124

5. Install libmagic (`./ihaskell-display/ihaskell-magic` seems to need this):
   ``` shell
   $ brew install libmagic
   ```

And now building (see the command under Step 1 above) worked (took a while, though, with 157 things to build).

I did get a warning after the build that `ihaskell` is linked to `~/.local/bin/ihaskell`,
which is good to know, since after the build, you then need to run
``` shell
$ ~/.local/bin/ihaskell install --stack
```
Finally, after starting a Jupyter server with
``` shell
$ stack exec jupyter -- notebook
```
I could open a notebook with an IHaskell language kernel, and everything worked again!

**Comment by vaibhavsagar** [comment]
1. As you noted, this is mentioned in our README.

2. That's strange that it works in CI for us but not for you. I've updated the version of `Chart-cairo` we pull in with https://github.com/IHaskell/IHaskell/pull/1436.

3. This is macOS-specific, nothing we can do about it here.

4. Same as 3.

> I did get a warning after the build that ihaskell is linked to `~/.local/bin/ihaskell`

That's [a Stack feature](https://docs.haskellstack.org/en/stable/GUIDE/#the-stack-install-command-and-copy-bins-option).

It sounds like you got everything working in the end, so I will go ahead and close this. Please reopen if necessary.
