### ISSUE TITLE
Running on Docker: iHaskell.Display not found

### ISSUE THREAD

**Issue by bmcollier** [IHaskell/IHaskell#1475]
Hi, I can build from the Dockerfile, but when attempting to replicate the demo notebook, I get the following when trying to import IHaskell.Display:

`<interactive>:1:1: error:
    Could not find module ‘IHaskell.Display’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
`

I'm afraid it's been rather a long time since I've used Haskell, so I'm probably making a stupid mistake somewhere. I tried uncommenting - ./ihaskell-display/ihaskell-static-canvas from the stack.yaml, but that doesn't seem to have made any difference.

I'd be grateful for some pointers.

**Comment by vaibhavsagar** [comment]
In the interest of saving space, the Docker image does not include the display packages. This unfortunately means that running the demo notebook from a fresh Docker container will not work. How are you trying to use the Docker container?

**Comment by bmcollier** [comment]
Oh, I'm literally doing a docker build and running it with the port exposed (as per the README). How does one go about adding the display packages from the command line? Theoretically, I can just add that to the Dockerfile. I'd be happy to make a pull request afterwards to the README.md with a short line to explain how to add those packages in case anyone else wants to do the same thing.

**Comment by jamesdbrock** [comment]
Here's a docker file which includes all packages including `Display`: https://github.com/IHaskell/ihaskell-notebook

**Comment by bmcollier** [comment]
Brilliant, thanks.
