### ISSUE TITLE
Syntax highlight not working with jupyterlab 4.1.6

### ISSUE THREAD

**Issue by ayanamists** [IHaskell/IHaskell#1488]
#1228 reported that syntax highlight does now work as expected. This problem should be fixed now.

However, I encounter such problem after setup (I followed the [instruction](https://github.com/IHaskell/IHaskell?tab=readme-ov-file#linux)). The kernel itself seems work fine, but no syntax highlight found.

<img width="1078" alt="截屏2024-04-26 10 29 57" src="https://github.com/IHaskell/IHaskell/assets/44194981/1ac03589-adec-408c-b6d0-1e92195094a0">

I guess this problem relates to the error thrown in browser:

```
Plugin 'ihaskell' failed to activate.
```

<img width="659" alt="image" src="https://github.com/IHaskell/IHaskell/assets/44194981/620043d7-7af0-4613-a288-9308dbd83cd0">

The problem here is the `requires` property of `t` is `[undefined]`, which lead to an exception in `this.resolveRequiredService(e)`. This property seems to be defined [here](https://github.com/IHaskell/IHaskell/blob/b223a6c2d0d0e812c4d77c062cc82ac7df8f8eca/jupyterlab-ihaskell/src/index.ts#L10)

I have no idea why `IEditorLanguageRegistry` is undefined.

<img width="912" alt="截屏2024-04-26 10 45 47" src="https://github.com/IHaskell/IHaskell/assets/44194981/d21d2981-8892-4205-b199-ac11b75a8fdb">

My jupyter version:

```
❯ jupyter --version
Selected Jupyter core packages...
IPython          : 8.23.0
ipykernel        : 6.29.4
ipywidgets       : not installed
jupyter_client   : 8.6.1
jupyter_core     : 5.7.2
jupyter_server   : 2.14.0
jupyterlab       : 4.1.6
nbclient         : 0.10.0
nbconvert        : 7.16.3
nbformat         : 5.10.4
notebook         : 7.1.3
qtconsole        : not installed
traitlets        : 5.14.3
```

**Comment by vaibhavsagar** [comment]
How did you install the `ihaskell-jupyterlab` extension? Can you confirm that it was installed by `ihaskell` during the installation process, or did you install it separately?

**Comment by ayanamists** [comment]
> How did you install the `ihaskell-jupyterlab` extension? Can you confirm that it was installed by `ihaskell` during the installation process, or did you install it separately?

It was installed by `ihaskell install --stack`, I do not install it separately. May I build a docker image to reproduce this problem?

**Comment by vaibhavsagar** [comment]
Sure, if you send me a link to a Docker image I can download and poke around locally.

**Comment by vaibhavsagar** [comment]
Were you able to reproduce the issue in a Docker image?

**Comment by ayanamists** [comment]
> Were you able to reproduce the issue in a Docker image?

I could not reproduce it for now. I'll try to reproduce it when I have time.

**Comment by vaibhavsagar** [comment]
Closing, please reopen (or create a new issue) if required.
