### ISSUE TITLE
Import IHaskell packages in notebook outside IHaskell folder

### ISSUE THREAD

**Issue by belonesox** [IHaskell/IHaskell#1492]
I am new in Haskell stack. 
- I installed IHaskell
- `IHaskell/notebooks/IHaskell.ipynb` works ok for me in Jupyter nodebook, vscode, code-server.
- When I move `IHaskell.ipynb` it outside `IHaskell` folder (say `~/test`), I got `Could not find module ‘IHaskell.Display’`

Looks I have somehow describe dependencies to all `./ihaskell-display/*` packages, how should I do it?
By `stack.yaml` (but I dont want to install any packages,  only use installed), `cabal.project`, `ihaskell.cabal`?
Please, show an example...

**Comment by vaibhavsagar** [comment]
Can you try https://github.com/IHaskell/IHaskell/issues/792#issuecomment-349186483?

**Comment by vaibhavsagar** [comment]
Closing, please reopen if required.
