### ISSUE TITLE
Interface not opening in VSCode

### ISSUE THREAD

**Issue by KeyPaganRush** [IHaskell/IHaskell#1503]
I did the following on Ubuntu, WSL.

```
sudo apt-get install -y python3-pip git libtinfo-dev libzmq3-dev libcairo2-dev libpango1.0-dev libmagic-dev libblas-dev liblapack-dev
curl -sSL https://get.haskellstack.org/ | sh
git clone https://github.com/gibiansky/IHaskell
cd IHaskell
pip3 install -r requirements.txt
stack install --fast
ihaskell install --stack
```

However, at ihaskell install --stack, I noticed no output was given in the terminal

When I tried opening the kernel in VSCode, it just kept returning these errors:

6:07:32.812 [error] Disposing session as kernel process died ExitCode: 1, Reason: ihaskell: <interactive>:1:1: error:
    Bad interface file: /home/~/IHaskell/.stack-work/install/x86_64-linux-tinfo6/a676e87e2105c62b8866a7906fabfa3a54a026e0a18660b5060303665d45c4ac/9.6.5/lib/x86_64-linux-ghc-9.6.5/ihaskell-aeson-0.3.0.1-AhAO1EBA6bGDwTn5hW5zYt/IHaskell/Display/Aeson.hi
        mismatched interface file versions (wanted "9064", got "9065")

**Comment by vaibhavsagar** [comment]
As indicated in your error message, this is caused by mismatched GHC versions as described here: https://github.com/IHaskell/IHaskell?tab=readme-ov-file#the-kernel-keeps-dying-ihaskell--stack
