### ISSUE TITLE
Run more than one version of IHaskell?

### ISSUE THREAD

**Issue by dabro** [IHaskell/IHaskell#710]
Is it possible to build and run ihaskell on different GHC versions?  eg 7.10.1 and 7.10.3?  If you try doing so, each overwrites the other's `ihaskell` binary in `.local/bin`.  It's easy to save a copy, but the location seems to be hardwired in?

**Comment by leftaroundabout** [comment]
The path is “hard-wired” only in `~/.local/share/jupyter/kernels/haskell/kernel.json`. It should be possible to make multiple different IHaskell kernels by `cp -r `~/.local/share/jupyter/kernels/{haskell,haskell-7.10.1}` and editing that file accordingly in one version.

**Comment by miguel-negrao** [comment]
With the nix package manager you can also change ghc version without issues with overwrites.
